site_name: "EcoSmart"
site_author: "Iv치n Dario Sanchez Fonseca"
site_url: https://eobs-mide.github.io/EcoSmart/
repo_url: https://github.com/idsanchezf

theme:
  #name: "material"
  name: "readthedocs"
  custom_dir: overrides/
  features:
    - navigation.tabs
    - navigation.sections
extra:
  version:
    provider: mike
    label: 1.0.0
nav:
  - 1. Evaluaci칩n de la Situaci칩n Actual: 
    - Recorrido actual del cliente: situacionActual/SituacionActual.md
    - Perfiles de cliente clave: situacionActual/PerfilCliente.md
  - 2. Definici칩n de Objetivos y Estrategia:
    - Objetivos estrategicos: objetivosEstrategia/ObjetivosEstrategicos.md
    - Modelo de trabajo: objetivosEstrategia/ModeloTrabajo.md
  - 3. Mapa de la Experiencia del Cliente Futura:
    - Recorrido ideal del cliente: situacionIdeal/mapaExperienciaFutura.md
    #- Estrategia de marketing digital: objetivosEstrategia/EstrategiaMarketingDigital.md
plugins:
  - search
  - mermaid2
  - panzoom
extra_css:
  - extra.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
